###
#  Serverless Typescript Example 
###

service: sls-ts-sample
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

  environment:
    LOG_LEVEL: info

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-jest-plugin

functions:
  hello:
    handler: src/app.hello
    events:
     - http:
         path: /hello
         method: get